/// Flutter icons BlueMotes
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BlueMotes
///      fonts:
///       - asset: fonts/BlueMotes.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RiftPlusIcons {
  RiftPlusIcons._();

  static const _kFontFam = 'RiftPlusIcons';
  static const _kFontPkg = null;

  static const IconData artboard___36 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shieldbreak = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speed = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData criticalstrike = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData detail_arrow = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magicpenetration = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magicdamage = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abilitypower = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData physicalvamp = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthplus = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData physicaldamage = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mana = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cooldown = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attackspeed = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wild_cores = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tank = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mage = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assasin = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData champion = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData runebeta = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData items = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allroles = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fighter = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marksman = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData energy = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magicalvamp = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData levelup = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mana_1 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baron_lane_icon = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dragon_lane_icon = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jungle_lane_icon = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mid_lane_icon = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData melee = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ranged = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData save = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duo_role = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jungle_role = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mid_role = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solo_role = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support_role = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
